import 'package:gh_battle_assistant/models/enums/unit_type.dart';

class ImageService {
  static const unitImageBaseUrl = 'assets/unit_images/';
  final unitImageMap = <UnitType, String>{
    UnitType.ancientArtillery: '${ImageService.unitImageBaseUrl}Ancient-Artillery-214x300.jpg',
    UnitType.banditArcher: '${ImageService.unitImageBaseUrl}Bandit-Archer-214x300.jpg',
    UnitType.banditGuard: '${ImageService.unitImageBaseUrl}Bandit-Guard-214x300.jpg',
    UnitType.banditLeader: '${ImageService.unitImageBaseUrl}Bandit-Leader-214x300.jpg',
    UnitType.blackImp: '${ImageService.unitImageBaseUrl}Black-Imp-214x300.jpg',
    UnitType.caveBear: '${ImageService.unitImageBaseUrl}Cave-Bear-214x300.jpg',
    UnitType.cityArcher: '${ImageService.unitImageBaseUrl}City-Archer-214x300.jpg',
    UnitType.cityGuard: '${ImageService.unitImageBaseUrl}City-Guard-214x300.jpg',
    UnitType.cultist: '${ImageService.unitImageBaseUrl}Cultist-214x300.jpg',
    UnitType.darkRider: '${ImageService.unitImageBaseUrl}Dark-Rider-small-214x300.jpg',
    UnitType.deepTerror: '${ImageService.unitImageBaseUrl}Deep-Terror-214x300.jpg',
    UnitType.earthDemon: '${ImageService.unitImageBaseUrl}Earth-Demon-214x300.jpg',
    UnitType.elderDrake: '${ImageService.unitImageBaseUrl}Elder-Drake-214x300.jpg',
    UnitType.flameDemon: '${ImageService.unitImageBaseUrl}Flame-Demon-214x300.jpg',
    UnitType.forestImp: '${ImageService.unitImageBaseUrl}Forest-Sprite-214x300.jpg',
    UnitType.frostDemon: '${ImageService.unitImageBaseUrl}Frost-Demon-214x300.jpg',
    UnitType.giantViper: '${ImageService.unitImageBaseUrl}Giant-Viper-214x300.jpg',
    UnitType.guardCaptain: '${ImageService.unitImageBaseUrl}Guard-Captain-214x300.jpg',
    UnitType.harrowerInfester: '${ImageService.unitImageBaseUrl}Harrower-Infester-214x300.jpg',
    UnitType.hound: '${ImageService.unitImageBaseUrl}Hound-214x300.jpg',
    UnitType.inoxArcher: '${ImageService.unitImageBaseUrl}Inox-Archer-214x300.jpg',
    UnitType.inoxBodyguard: '${ImageService.unitImageBaseUrl}Inox-Bodyguard-214x300.jpg',
    UnitType.inoxGuard: '${ImageService.unitImageBaseUrl}Inox-Guard-214x300.jpg',
    UnitType.inoxShaman: '${ImageService.unitImageBaseUrl}Inox-Shaman-214x300.jpg',
    UnitType.jekserah: '${ImageService.unitImageBaseUrl}Jekserah-214x300.jpg',
    UnitType.livingBones: '${ImageService.unitImageBaseUrl}Skeleton-214x300.jpg',
    UnitType.livingDead: '${ImageService.unitImageBaseUrl}Zombie-214x300.jpg',
    UnitType.livingSpirit: '${ImageService.unitImageBaseUrl}Ghost-214x300.jpg',
    UnitType.lurker: '${ImageService.unitImageBaseUrl}Lurker-214x300.jpg',
    UnitType.mercilessOverseer: '${ImageService.unitImageBaseUrl}Merciless-Overseer-214x300.jpg',
    UnitType.nightDemon: '${ImageService.unitImageBaseUrl}Night-Demon-214x300.jpg',
    UnitType.ooze: '${ImageService.unitImageBaseUrl}Ooze-214x300.jpg',
    UnitType.primeDemon: '${ImageService.unitImageBaseUrl}Prime-Demon-214x300.jpg',
    UnitType.rendingDrake: '${ImageService.unitImageBaseUrl}Vicious-Drake-214x300.jpg',
    UnitType.savassIcestorm: '${ImageService.unitImageBaseUrl}Savvas-Icestorm-214x300.jpg',
    UnitType.savassLavaflow: '${ImageService.unitImageBaseUrl}Savvas-Lavaflow-214x300.jpg',
    UnitType.spiritDrake: '${ImageService.unitImageBaseUrl}Spitting-Drake-214x300.jpg',
    UnitType.stoneGolem: '${ImageService.unitImageBaseUrl}Stone-Golem-214x300.jpg',
    UnitType.sunDemon: '${ImageService.unitImageBaseUrl}Sun-Demon-214x300.jpg',
    UnitType.bertayer: '${ImageService.unitImageBaseUrl}The-Bertayer-214x300.jpg',
    UnitType.colorless: '${ImageService.unitImageBaseUrl}The-Colorless-214x300.jpg',
    UnitType.gloom: '${ImageService.unitImageBaseUrl}The-Gloom-214x300.jpg',
    UnitType.sightlessEye: '${ImageService.unitImageBaseUrl}The-Sightless-Eye-214x300.jpg',
    UnitType.vermlingScout: '${ImageService.unitImageBaseUrl}Vermling-Scout-214x300.jpg',
    UnitType.vermlingShaman: '${ImageService.unitImageBaseUrl}Vermling-Shaman-214x300.jpg',
    UnitType.windDemon: '${ImageService.unitImageBaseUrl}Wind-Demon-214x300.jpg',
    UnitType.wingedHorror: '${ImageService.unitImageBaseUrl}Winged-Horror-214x300.jpg',
  };

  String getUnitImageByType(UnitType type) => unitImageMap[type] ?? '';
}
